; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "EBT Weather"
#define MyAppVersion "1.03"
#define MyAppPublisher "Eric Bergman-Terrell"
#define MyAppURL "https://www.EricBT.com/"
#define MyAppExeName "EBTWeather.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8F43100B-AC4F-4826-82A0-B8C11AB8909F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={commonpf64}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=EBT Weather Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon="{app}\{#MyAppExeName}"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Base.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Controls.DataGrid.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Controls.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.DesignerSupport.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Desktop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Dialogs.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Fonts.Inter.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.FreeDesktop.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Markup.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Markup.Xaml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Metal.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.MicroCom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Native.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.OpenGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Remote.Protocol.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Skia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Themes.Fluent.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Vulkan.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Win32.Automation.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.Win32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Avalonia.X11.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\CommunityToolkit.Mvvm.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\DialogHost.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\EBTWeather.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\EBTWeather.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\EBTWeather.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\EBTWeather.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\EBTWeather.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\HarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\log4net.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\log4net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\MicroCom.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Caching.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Caching.Hybrid.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Caching.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Configuration.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Configuration.Binder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Diagnostics.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Diagnostics.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Http.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Http.Polly.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Options.ConfigurationExtensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\MsBox.Avalonia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Polly.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Polly.Extensions.Http.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\SkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\System.Security.Cryptography.ProtectedData.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\System.Security.Permissions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\Tmds.DBus.Protocol.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\UnitsNet.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\fr-CA\UnitsNet.resources.dll"; DestDir: "{app}\fr-CA"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\nb-NO\UnitsNet.resources.dll"; DestDir: "{app}\nb-NO"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\ru-RU\UnitsNet.resources.dll"; DestDir: "{app}\ru-RU"; Flags: ignoreversion
Source: "C:\Users\erict\Documents\software development\Avalonia UI\EBTWeather\EBTWeather.Avalonia\bin\Release\net10.0\win-x64\publish\zh-CN\UnitsNet.resources.dll"; DestDir: "{app}\zh-CN"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

